import { useEffect, useRef, useState } from "react";
import { Link, useParams } from "react-router-dom";
import ReactMarkdown from "react-markdown";
import { Bot, Copy, MessageSquarePlus, SendHorizontal, UserRound } from "lucide-react";
import Loader from "../components/Loader";
import { api, streamMessage } from "../services/api";

export default function Chat() {
  const { repositoryId } = useParams();
  const [repo, setRepo] = useState(null), [sessions, setSessions] = useState([]), [session, setSession] = useState(null), [messages, setMessages] = useState([]);
  const [input, setInput] = useState(""), [loading, setLoading] = useState(true), [sending, setSending] = useState(false), [error, setError] = useState(""), [copied, setCopied] = useState("");
  const listRef = useRef(null), bottomRef = useRef(null), autoScroll = useRef(true);
  useEffect(() => { (async () => { try { const [repository, chatSessions] = await Promise.all([api.getRepository(repositoryId), api.getSessions(repositoryId)]); setRepo(repository); setSessions(chatSessions); if (chatSessions[0]) { setSession(chatSessions[0]); setMessages(await api.getMessages(chatSessions[0].id)); } } catch (e) { setError(e.message); } finally { setLoading(false); } })(); }, [repositoryId]);
  useEffect(() => { if (autoScroll.current) bottomRef.current?.scrollIntoView({ behavior: "smooth", block: "end" }); }, [messages]);
  const select = async (item) => { setSession(item); setError(""); try { setMessages(await api.getMessages(item.id)); } catch (e) { setError(e.message); } };
  const create = async () => { try { const next = await api.createSession(repositoryId); setSessions((old) => [next, ...old]); setSession(next); setMessages([]); } catch (e) { setError(e.message); } };
  const send = async (event) => { event.preventDefault(); const content = input.trim(); if (!content || sending) return; setInput(""); setSending(true); setError(""); const temp = `temporary-${Date.now()}`; let output = ""; setMessages((old) => [...old, { id: temp, role: "USER", content }, { id: `${temp}-assistant`, role: "ASSISTANT", content: "" }]); try { let active = session; if (!active) { active = await api.createSession(repositoryId, content.slice(0, 60)); setSession(active); setSessions((old) => [active, ...old]); } await streamMessage(active.id, content, { onUserMessage: (message) => setMessages((old) => old.map((item) => item.id === temp ? message : item)), onToken: (token) => { output += token; setMessages((old) => old.map((item) => item.id === `${temp}-assistant` ? { ...item, content: output } : item)); }, onAssistantMessage: (message) => setMessages((old) => old.map((item) => item.id === `${temp}-assistant` ? message : item)) }); } catch (e) { setError(e.message); setMessages((old) => old.filter((item) => item.id !== `${temp}-assistant`)); } finally { setSending(false); } };
  const copy = async (content, id) => { await navigator.clipboard?.writeText(content); setCopied(id); window.setTimeout(() => setCopied(""), 1200); };
  if (loading) return <Loader fullScreen label="Loading chat..." />;
  if (error && !repo) return <div className="notice error">{error}</div>;
  return <section className="chat-page"><header className="chat-header"><Link className="back-link" to="/dashboard">{repo?.fullName}</Link><h1>Repository chat</h1></header><div className="chat-layout"><aside className="session-list"><div className="session-list-heading"><span>Conversations</span><button type="button" onClick={create} aria-label="New conversation"><MessageSquarePlus /></button></div>{sessions.length === 0 && <p className="muted small-text">Your conversations will appear here.</p>}{sessions.map((item) => <button className={session?.id === item.id ? "session active" : "session"} key={item.id} onClick={() => select(item)}>{item.title}</button>)}</aside><div className="chat-panel"><div className="messages" ref={listRef} onScroll={() => { const el = listRef.current; if (el) autoScroll.current = el.scrollHeight - el.scrollTop - el.clientHeight < 96; }}>{messages.length === 0 && <div className="chat-empty"><Bot className="hero-icon" /><h2>Ask about your code</h2><p className="muted">Ask about architecture, behavior, or a specific file.</p></div>}{messages.map((message, index) => <article className={`message ${message.role?.toLowerCase()}`} key={message.id || index}><div className="message-label">{message.role === "USER" ? <><UserRound /> You</> : <><Bot /> RepoChat</>}</div><div className="message-body">{message.role === "USER" ? message.content : message.content ? <ReactMarkdown>{message.content}</ReactMarkdown> : <span className="thinking">Thinking...</span>}</div>{message.content && <button className="copy-button" type="button" onClick={() => copy(message.content, message.id)}>{copied === message.id ? "Copied" : <Copy />}</button>}{message.citations?.length > 0 && <div className="citations">{message.citations.map((citation, i) => <span key={i}>{citation.filePath}{citation.startLine ? `:${citation.startLine}` : ""}</span>)}</div>}</article>)}<div ref={bottomRef} /></div>{error && <div className="inline-error">{error}</div>}<form className="composer" onSubmit={send}><textarea value={input} onChange={(e) => setInput(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); send(e); } }} placeholder="Ask about architecture, files, or flows..." rows="2" disabled={sending} /><button className="button primary icon-button" disabled={sending || !input.trim()} aria-label="Send message"><SendHorizontal /></button></form><p className="composer-hint">Press Enter to send. Shift + Enter for a new line.</p></div></div></section>;
}
